micromips/micromips/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('processor.urls')),
]

micromips/processor/urls.py
from django.conf.urls import url
from . import views

app_name = 'processor'

urlpatterns = [

	url(r'^$', views.index, name='index'),
	url(r'^initialize/$', views.initialize, name='initialize'),
	url(r'^reginput/$', views.regInput, name='regInput'),
	url(r'^meminput/$', views.memInput, name='memInput'),
]

micromips/processor/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Register(models.Model):
	value = models.CharField(default="0000000000000000", max_length=16)

	def __str__(self):
		return str(self.id)

class DataSegment(models.Model):
	addr = models.CharField(blank=True, max_length=4)
	value = models.CharField(default="0000000000000000", max_length=16)

	def __str__(self):
		return str(self.addr)

class MipsProgram(models.Model):
	addr = models.CharField(blank=True, max_length=4)
	opcode = models.CharField(blank=True, max_length=8)
	label = models.CharField(blank=True, max_length=20)
	instruction = models.CharField(blank=True, max_length=50)
	cmd = models.CharField(blank=True, max_length=20)
	dest = models.CharField(blank=True, max_length=4)
	src1 = models.CharField(blank=True, max_length=4)
	src2 = models.CharField(blank=True, max_length=4)
	jumpTo = models.CharField(blank=True, max_length=20)

	def __str__(self):
		return str(self.addr)
	

micromips/processor/views.py
from __future__ import unicode_literals
from django.shortcuts import render, redirect
import re, binascii
from .models import Register, DataSegment, MipsProgram

def index(request):
	progObjects = MipsProgram.objects.all()
	error = False

	if request.method == 'POST':
		MipsProgram.objects.all().delete()

		try:
			commands = request.POST['commands']
			cmdarr = commands.splitlines()
			output = []
			hexoutput = []
			pipeline = []
			i = 0
			label = ''

			for index, command in enumerate(cmdarr):
				temp = []
				dependent = -1

				if ': ' in command:
					label = str(command.split(": ", 1)[0])
					cmd = str(str(command.split(": ", 1)[1]).split(" ", 1)[0])
				elif ':' in command:
					label = str(command.split(":", 1)[0])
					cmd = str(str(command.split(":", 1)[1]).split(" ", 1)[0])
				else:
					cmd = str(command.split(" ", 1)[0])

				if cmd == 'J':
					var1 = str(command.split(" ", 1)[1])
				else:
					var1 = str(re.split(', ', command.split(" ", 1)[1])[0].split("R", 1)[1])
					if int(var1) < 0 or int(var1) > 31:
						error = True
						MipsProgram.objects.all().delete()
						break;

					if cmd == "LD" or cmd == "SD":
						var2 = str(re.split(', |\(|\)', command.split(" ", 1)[1])[1])
						var3 = str(re.split(', |\(|\)', command.split(" ", 1)[1])[2].split("R", 1)[1])

					elif cmd == 'BEQC':
						var2 = str(re.split(', ', command.split(" ", 1)[1])[1].split("R", 1)[1])
						var3 = str(re.split(', ', command.split(" ", 1)[1])[2])

					else:
						var2 = str(re.split(', ', command.split(" ", 1)[1])[1].split("R", 1)[1])
						var3 = str(re.split(r'R|#', re.split(', ', command.split(" ", 1)[1])[2])[1])

				if cmd == "LD":
					output.append('110111'+ format(int(var3), '05b') + format(int(var1), '05b') + format(int(var2[0], 16), '04b') + format(int(var2[1], 16), '04b') + format(int(var2[2], 16), '04b') + format(int(var2[3], 16), '04b'))

				elif cmd == "SD":
					output.append('111111' + format(int(var3), '05b') + format(int(var1), '05b') + format(int(var2[0], 16), '04b') + format(int(var2[1], 16), '04b') + format(int(var2[2], 16), '04b') + format(int(var2[3], 16), '04b'))

				elif cmd == "DADDIU":
					output.append('011001' + format(int(var2), '05b') + format(int(var1), '05b') + format(int(var3[0], 16), '04b') + format(int(var3[1], 16), '04b') + format(int(var3[2], 16), '04b') + format(int(var3[3], 16), '04b'))

				elif cmd == "XORI":
					output.append('001110' + format(int(var2), '05b') + format(int(var1), '05b') + format(int(var3[0], 16), '04b') + format(int(var3[1], 16), '04b') + format(int(var3[2], 16), '04b') + format(int(var3[3], 16), '04b'))

				elif cmd == "DADDU":
					output.append('000000' + format(int(var2), '05b') + format(int(var3), '05b') + format(int(var1), '05b') + '00000101101')

				elif cmd == "SLT":
					output.append('000000' + format(int(var2), '05b') + format(int(var3), '05b') + format(int(var1), '05b') + '00000101010')

				elif cmd == 'BEQC':
					for index2, cmd2 in enumerate(cmdarr[index:]):
						if ':' in cmd2:
							label2 = str(cmd2.split(":", 1)[0])
							if label2 == var3:
								output.append('001000' + format(int(var1), '05b') + format(int(var2), '05b') + format(int(index2-1), '016b'))
				
				elif cmd == 'J':
					for index2, cmd2 in enumerate(cmdarr):
						if ':' in cmd2:
							label2 = str(cmd2.split(":", 1)[0])
							if label2 == var1:
								output.append('000010' + format(int(index2), '026b'))

				else:
					error = True
					MipsProgram.objects.all().delete()
					break;

				if not label == '':
					if cmd == "LD" or cmd == "DADDIU" or cmd == "XORI" or cmd == "SLT" or cmd == "DADDU":
						MipsProgram.objects.create(id=i, addr='1' + str(format((len(output) - 1) * 4, '03x')).upper(), opcode=str(format(int(output[-1], 2), '08x')).upper(), label=label, instruction=command, cmd=cmd, dest=var1, src1=var2, src2=var3)
					elif cmd == "SD":
						MipsProgram.objects.create(id=i, addr='1' + str(format((len(output) - 1) * 4, '03x')).upper(), opcode=str(format(int(output[-1], 2), '08x')).upper(), label=label, instruction=command, cmd=cmd, dest=var2, src1=var1, src2=var3)
					elif cmd == "BEQC":
						MipsProgram.objects.create(id=i, addr='1' + str(format((len(output) - 1) * 4, '03x')).upper(), opcode=str(format(int(output[-1], 2), '08x')).upper(), label=label, instruction=command, cmd=cmd, src1=var1, src2=var2, jumpTo=var3)
					elif cmd == "J":
						MipsProgram.objects.create(id=i, addr='1' + str(format((len(output) - 1) * 4, '03x')).upper(), opcode=str(format(int(output[-1], 2), '08x')).upper(), label=label, instruction=command, cmd=cmd, jumpTo=var1)
				else:
					if cmd == "LD" or cmd == "DADDIU" or cmd == "XORI" or cmd == "SLT" or cmd == "DADDU":
						MipsProgram.objects.create(id=i, addr='1' + str(format((len(output) - 1) * 4, '03x')).upper(), opcode=str(format(int(output[-1], 2), '08x')).upper(), instruction=command, cmd=cmd, dest=var1, src1=var2, src2=var3)
					elif cmd == "SD":
						MipsProgram.objects.create(id=i, addr='1' + str(format((len(output) - 1) * 4, '03x')).upper(), opcode=str(format(int(output[-1], 2), '08x')).upper(), instruction=command, cmd=cmd, dest=var2, src1=var1, src2=var3)
					elif cmd == "BEQC":
						MipsProgram.objects.create(id=i, addr='1' + str(format((len(output) - 1) * 4, '03x')).upper(), opcode=str(format(int(output[-1], 2), '08x')).upper(), instruction=command, cmd=cmd, src1=var1, src2=var2, jumpTo=var3)
					elif cmd == "J":
						MipsProgram.objects.create(id=i, addr='1' + str(format((len(output) - 1) * 4, '03x')).upper(), opcode=str(format(int(output[-1], 2), '08x')).upper(), instruction=command, cmd=cmd, jumpTo=var1)

				hexoutput.append(str(format(int(output[-1], 2), '08x')).upper())

				i += 1

			

			progObjects = MipsProgram.objects.all()
# START OF INTERNAL REGISTER
			lastProg = MipsProgram.objects.get(id=progObjects.count()-1)
			if lastProg.cmd == 'LD':
				address = format(int(int(lastProg.src1, 16) + int(int(Register.objects.get(id=int(lastProg.src2)).value, 16)/8)*8), '04x')
				reg = 'R' + str(lastProg.dest)
				wb = DataSegment.objects.get(addr=address).value
			elif lastProg.cmd == 'SD' or lastProg.cmd == 'BEQC' or lastProg.cmd == 'J':
				reg = ''
				wb = 'N/A'
			elif lastProg.cmd == 'DADDIU':
				immediate = int(Register.objects.get(id=int(lastProg.src1)).value, 16) + int(format(int(str(lastProg.src2)[0], 16), '04b') + format(int(str(lastProg.src2)[1], 16), '04b') + format(int(str(lastProg.src2)[2], 16), '04b') + format(int(str(lastProg.src2)[3], 16), '04b'), 2)
				hexcode = format(immediate, '04x').upper()

				if (binascii.unhexlify(hexcode))[0] == '1':
					wb = str("FFFFFFFFFFFF" + hexcode)
				else:
					wb = str('000000000000' + hexcode)
				reg = 'R' + str(lastProg.dest)
				print(wb)
			elif lastProg.cmd == 'XORI':
				immediate = format(int(str(lastProg.src2)[0], 16), '04b') + format(int(str(lastProg.src2)[1], 16), '04b') + format(int(str(lastProg.src2)[2], 16), '04b') + format(int(str(lastProg.src2)[3], 16), '04b')
				val = format(int(Register.objects.get(id=int(lastProg.src1)).value, 16), '016b')
				binary = ''
				for count in range(len(immediate)):
					if immediate[count] != val[count]:
						binary += '1'
					else:
						binary += '0'

				reg = 'R' + str(lastProg.dest)
				wb = format(int(binary, 2), '016x').upper()
				print(wb)
			elif lastProg.cmd == 'DADDU':
				operation = int(Register.objects.get(id=int(lastProg.src1)).value, 16) + int(Register.objects.get(id=int(lastProg.src2)).value, 16)
				reg = 'R' + str(lastProg.dest)
				wb = format(operation, '016x')
				print(wb)
			elif lastProg.cmd == 'SLT':
				operation = int(Register.objects.get(id=int(lastProg.src1)).value, 16) < int(Register.objects.get(id=int(lastProg.src2)).value, 16)
				if operation:
					wb = format(int(Register.objects.get(id=int(lastProg.src1)).value, 16), '016x')
					reg = 'R' + str(lastProg.dest)
				else:
					wb = ''
					reg = ''

			for program in progObjects:
				if program.cmd == 'LD':
					address = format(int(int(program.src1, 16) + int(int(Register.objects.get(id=int(program.src2)).value, 16)/8)*8), '04x')
					wback = DataSegment.objects.get(addr=address).value
					regObj = Register.objects.get(id=int(program.dest))
					regObj.value = wback
					regObj.save()
				elif program.cmd == 'SD':
					address = format(int(int(program.dest, 16) + int(int(Register.objects.get(id=int(program.src2)).value, 16)/8)*8), '04x')
					print(address)
					wback = Register.objects.get(id=int(program.src1)).value
					memObj = DataSegment.objects.get(addr=str(address))
					memObj.value = wback
					memObj.save()

				elif program.cmd == 'BEQC' or program.cmd == 'J':
					wback = 'N/A'
				elif program.cmd == 'DADDIU':
					immediate = int(Register.objects.get(id=int(program.src1)).value, 16) + int(format(int(str(program.src2)[0], 16), '04b') + format(int(str(program.src2)[1], 16), '04b') + format(int(str(program.src2)[2], 16), '04b') + format(int(str(program.src2)[3], 16), '04b'), 2)
					hexcode = format(immediate, '04x').upper()
					print("DADDIU")
					if (binascii.unhexlify(hexcode))[0] == '1':
						wback = str("FFFFFFFFFFFF" + hexcode)
					else:
						wback = str('000000000000' + hexcode)
					regObj = Register.objects.get(id=int(program.dest))
					regObj.value = wback
					regObj.save()
				elif program.cmd == 'XORI':
					immediate = str(format(int(str(program.src2)[0], 16), '04b') + format(int(str(program.src2)[1], 16), '04b') + format(int(str(program.src2)[2], 16), '04b') + format(int(str(program.src2)[3], 16), '04b'))
					val = str(format(int(Register.objects.get(id=int(program.src1)).value, 16), '016b'))
					print(immediate)
					print(val)
					binary = ''
					for count in range(len(immediate)):
						if immediate[count] != val[count]:
							binary += '1'
						else:
							binary += '0'
					wback = format(int(binary, 2), '016x').upper()
					print(binary)
					regObj = Register.objects.get(id=int(program.dest))
					regObj.value = wback
					regObj.save()

micromips/processor/templates/processor/index.html
{% extends 'processor/extends/header.html' %}
{% load filterarrays %}

{% block scripts %}
  <script>
    $(document).ready(function() {
        var counter = 0;
        var numObject = "{{  objectCount|safe }}";

        $('.pipRows').hide();
        $('.pipelineCycles').hide();

        $("#fullbutton").click(function(){
            $('.pipRows').show();
            $('.pipelineCycles').show();
            $("#fullbutton").attr("disabled", 'true');
            $("#singlebutton").attr("disabled", 'true');
        });

        $("#singlebutton").click(function(){
          $('.pipelineCycles').eq(counter).show();
          for (var i = 0; i < parseInt(numObject); i++) {
            var str = '.pipelineRows' + counter.toString();
            $(str).show();
          }
          counter += 1;

        });

        

    });
  </script>

{% endblock %}

{% block body %}
  <table style="margin-left:10px;height:270px;width:100%;display:block;">
    <tr style="table-layout:fixed;">
      <td width=40% style="background:#fff; padding:1%;">
        {% if error %}
          <div class="alert alert-danger" role="alert">
            ERROR!
          </div>
        {% endif %}
        <div class="float-left">Please enter codes here</div>
        <form method="POST">
          {% csrf_token %}
          <button type="submit" class="btn btn-dark btn-sm float-right mb-3">Load ▶</button>
          <a class="btn btn-dark btn-sm float-right mb-3 mr-1" href="{% url 'processor:initialize' %}">Reset</a>
          <div>
            <textarea rows="10" cols="78" name="commands" style="width:100%; resize:none;">{% for prog in progObjects %}{{ prog.instruction }}&#13;&#10;{% endfor %}</textarea>
          </div>
        </form>
      </td>
      <td width=60% style="padding: 1%;">Opcode
        <table class="table table-sm" style="background:#272f45;color:#fff;width: 850px">
          <thead style="display:block;width:850px;">
            <tr>
              <th style="width:1%;" scope="col">Address</th>
              <th style="width:1%;" scope="col">Command</th>
              <th style="width:1%;" scope="col">Opcode</th>
            </tr>
          </thead>
          <tbody style="height:270px;display:block;width:850px;overflow:auto;">
            {% for prog in progObjects %}
            <tr>
              {% if not error %}
              <td style="width:1%;">{{ prog.addr }}</td>
              <td style="width:1%;">{{ prog.instruction }}</td>
              <td style="width:1%;">{{ prog.opcode }}</td>
              {% endif %}
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </td>
    </tr>
    <tr>
     <td style="padding: 1%;">Internal
        <table class="table table-sm table-bordered" style="background:#272f45;color:#fff;height:450px;display:block;width:100%;overflow:auto;">
          <thead>
            <tr>
              <th style="width:1%;" scope="col">Internal Registers</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>IF/ID.IR</td>
              <td>{{if_idIr}}</td>
            </tr>
            <tr>
              <td>IF/ID.NPC,PC</td>
              <td>{{if_idNpc}}</td>
            </tr>
            <tr>
              <td>ID/EX.A</td>
              <td>{{id_exA}}</td>
            </tr>
            <tr>
              <td>ID/EX.B</td>
              <td>{{id_exB}}</td>
            </tr>
            <tr>
              <td>ID/EX.NPC</td>
              <td>{{id_exNpc}}</td>
            </tr>
            <tr>
              <td>ID/EX.Imm</td>
            </tr>
            <tr>
              <td>EX/MEM.IR</td>
            </tr>
            <tr>
              <td>EX/MEM.ALUOutput</td>
            </tr>
            <tr>
              <td>EX/MEM.cond</td>
            </tr>
            <tr>
              <td>MEM/WB.IR</td>
            </tr>
            <tr>
              <td>MEM/WB.ALUOutput</td>
            </tr>
            <tr>
              <td>WB</td>
              <td>{{ reg }} = {{ wb }}</td>
            </tr>
          </tbody>
        </table>
      </td>

      <td style="padding: 1%;">Pipeline
        {% if pipeline %}
        <button id="fullbutton" type="button" class="btn btn-dark btn-sm float-right mb-3 mr-1">Full</button>
        <button id="singlebutton" type="button" class="btn btn-dark btn-sm float-right mb-3 mr-1">Single</button>
        {% endif %}
        <table id="pipeline" class="table table-sm table-bordered" style="background:#272f45;color:#fff;height:450px;display:block;width:850px;overflow:auto;">
          <thead>
            <tr>
              <th style="width:1%;" scope="col">Instruction</th>
              {% for p in pipLast %}<th class="pipelineCycles">{{ p }}</th>{% endfor %}
            </tr>
          </thead>
          <tbody>
            {% for prog in progObjects %}
            <tr>
              <td>{{ prog.instruction }}</td>
              {% if pipeline %}{% for pip in pipeline|index:forloop.counter0 %}<td class="pipelineRows{{forloop.counter0}} pipRows">{{ pip }}</td>{% endfor %}{% endif %}
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </td>
    </tr>
  </table>
{% endblock %}

micromips/processor/templates/processor/meminput.html
{% extends 'processor/extends/header.html' %}

{% block title %}
Memory Input
{% endblock %}

{% block scripts %}
<script>
    $(document).ready(function() {
        window.onscroll = function() {myFunction();};

            function myFunction() {
                if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
                    document.getElementById("up").style.visibility = "visible";
                } else {
                    document.getElementById("up").style.visibility = "hidden";
                }
            }

        $("#findbtn").click(function (){
            var given = $("#goToAddress").val();
            var x = parseInt(given, 16) / 8;
            var y = (parseInt(x) * 8).toString(16);
            while(y.length < 4){
                y = "0" + y;
            }
            y = y.toUpperCase();
            $('.bg-info').removeClass('bg-info');
            $('html, body').animate({
                scrollTop: (
                    $('#myTable th').filter(function() {
                        return $(this).text() == y;
                    }).closest('tr').addClass("bg-info").offset().top
                )
            },500);
        });
    });

    function topFunction() {
        $('html, body').animate({
            scrollTop: ($('body').offset().top)
        },500);

    }
    
</script>
{% endblock %}

{% block body %}
<div class="container m-5">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Memory Input</h5>
            <form method="POST">
                {% csrf_token %}
                <label class="sr-only" for="inlineFormInput">Memory Address</label>
                <input type="text" name="memAddr" class="form-control mb-2 mr-sm-2 mb-sm-0" id="inlineFormInput" placeholder="Enter address">

                <label class="sr-only" for="inlineFormInput">Value</label>
                <input type="text" name="memVal" class="form-control mb-2 mr-sm-2 mb-sm-0" id="inlineFormInput" placeholder="Enter value">
                <button class="btn btn-primary" type="submit">Submit</button>
            </form>
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Go To Memory</h5>
            <label class="sr-only" for="inlineFormInput">Address</label>
            <input type="text" id="goToAddress" class="form-control mb-2 mr-sm-2 mb-sm-0" id="inlineFormInput" placeholder="Enter address">
            <button id="findbtn" class="btn btn-primary">Find</button>
        </div>
    </div>

    <table id="myTable" class="table">
        <thead>
            <tr>
                <th scope="col">Memory</th>
                <th scope="col">Value</th>
            </tr>
        </thead>
        <tbody>
            {% for m in mem %}
            <tr class="clickable-row">
                <th scope="row" id="{{ m.addr }}">{{ m.addr }}</th>
                <td>{{ m.value }}</td>
            </tr>
            {% endfor %}
        </tbody>
  </table>
</div>
<div id="uparrow" class="icon" style="cursor: pointer;" onclick="topFunction();">
    <i id="up" class="fa fa-chevron-up"  style="visibility:hidden; position: fixed;
      bottom: 20px;
      right: 30px;
      z-index: 99;font-size:50px;"></i>
</div>
{% endblock %}

micromips/processor/templates/processor/reginput.html
{% extends 'processor/extends/header.html' %}

{% block title %}
Register Input
{% endblock %}

{% block body %}
<div class="container m-5">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Register Input</h5>
      <form method="POST">
        {% csrf_token %}
        <select class="custom-select" name="regNum">
          <option selected disabled></option>
          <option value="1">R1</option>
          <option value="2">R2</option>
          <option value="3">R3</option>
          <option value="4">R4</option>
          <option value="5">R5</option>
          <option value="6">R6</option>
          <option value="7">R7</option>
          <option value="8">R8</option>
          <option value="9">R9</option>
          <option value="10">R10</option>
          <option value="11">R11</option>
          <option value="12">R12</option>
          <option value="13">R13</option>
          <option value="14">R14</option>
          <option value="15">R15</option>
          <option value="16">R16</option>
          <option value="17">R17</option>
          <option value="18">R18</option>
          <option value="19">R19</option>
          <option value="20">R20</option>
          <option value="21">R21</option>
          <option value="22">R22</option>
          <option value="23">R23</option>
          <option value="24">R24</option>
          <option value="25">R25</option>
          <option value="26">R26</option>
          <option value="27">R27</option>
          <option value="28">R28</option>
          <option value="29">R29</option>
          <option value="30">R30</option>
          <option value="31">R31</option>
        </select>

        <label class="sr-only" for="inlineFormInput">Value</label>
        <input type="text" name="regVal" class="form-control mb-2 mr-sm-2 mb-sm-0" id="inlineFormInput" placeholder="Enter value">
        <button class="btn btn-primary" type="submit">Submit</button>
      </form>
    </div>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">Register</th>
        <th scope="col">Value</th>
      </tr>
    </thead>
    <tbody>
      {% for r in reg %}
      <tr>
        <th scope="row">R{{ r.id }}</th>
        <td>{{ r.value }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}